name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Build package
        run: python3 -m pip install --upgrade build && python3 -m build
      - name: Run tests
        run: python3 -m pip install --upgrade pytest && pytest tests/test_alto_tools.py
